apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv-new
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /tmp  # Path on the local node where the data will be stored
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - ip-172-31-25-27.ap-south-1.compute.internal  # Replace with the node where you want to store the data
  storageClassName: manual
